name: "RefineIt (run analyzer)"
description: "Run the RefineIt static analyzer. Optionally create a PR with fixes."
author: "RefineIt Team"
inputs:
  args:
    description: "Extra CLI args"
    required: false
    default: '--dry-run --export-report refineit-report.json'
  create-pr:
    description: "If 'true', create PR"
    required: false
    default: 'false'
  push-branch:
    description: "Branch name"
    required: false
    default: ''
  working-directory:
    description: "Path"
    required: false
    default: '.'
  push_token:
    description: "GitHub token"
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Move to working directory
      if: inputs.working-directory != '.'
      run: cd "${{ inputs.working-directory }}"
      shell: bash

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci --silent --no-audit --no-fund
          npm run build
        fi
      shell: bash

    - name: Run RefineIt analyzer
      id: run_refineit
      run: |
        set -e

        # Cleanup step to ensure the workspace is clean before the analysis
        rm -rf dist *.tsbuildinfo refineit-report.json refineit-debug.json || true
        git checkout . || true

        echo "Running: npx refineit ${{ inputs.args }}"
        # allow refineit to fail without failing the whole action (report will still be uploaded)
        npx refineit ${{ inputs.args }} || true
      shell: bash

    - name: Upload report artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: refineit-report
        path: |
          refineit-report.json
          refineit-debug.json
        retention-days: 7

    - name: Create branch & PR
      if: inputs.create-pr == 'true' && inputs.push_token != ''
      run: |
        set -euo pipefail

        # Ensure --apply is present (safety)
        echo "Verifying --apply present in args"
        echo "${{ inputs.args }}" | grep -q -- '--apply' || (echo "Refuse: --apply not present. Aborting." && exit 1)

        # Git identity (bot)
        git config user.name "refineit-bot"
        git config user.email "ci@refineit.local"

        # Inputs
        TARGET_BRANCH="${{ inputs.push-branch }}"
        if [ -z "$TARGET_BRANCH" ]; then
          TARGET_BRANCH="refineit/auto-fixes"
        fi
        BASE_BRANCH="main"

        # Use token-based remote URL for authenticated push
        REMOTE_URL="https://x-access-token:${{ inputs.push_token }}@github.com/${{ github.repository }}.git"
        git remote set-url origin "$REMOTE_URL"

        # Fetch latest refs (do NOT fetch into checked-out main ref)
        echo "Fetching latest from origin..."
        git fetch --no-tags --prune origin

        # Create branch from origin/BASE_BRANCH (safe even if local main is checked out)
        echo "Reset/prepare branch '$TARGET_BRANCH' from origin/$BASE_BRANCH..."
        if git show-ref --verify --quiet "refs/heads/$TARGET_BRANCH"; then
          git branch -D "$TARGET_BRANCH"
        fi

        # Checkout new branch from origin/BASE_BRANCH. If origin/BASE_BRANCH doesn't exist, fallback to local.
        if git ls-remote --exit-code --heads origin "$BASE_BRANCH" >/dev/null 2>&1; then
          git checkout -b "$TARGET_BRANCH" "origin/$BASE_BRANCH"
        else
          echo "Warning: origin/$BASE_BRANCH not found, checking out local $BASE_BRANCH instead."
          git fetch origin "$BASE_BRANCH" || true
          git checkout -b "$TARGET_BRANCH" "$BASE_BRANCH" || git checkout -b "$TARGET_BRANCH"
        fi

        # Commit any changes produced by `npx refineit --apply` step
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "refineit: apply suggested fixes" || echo "No commit (maybe nothing changed)."
        else
          echo "No changes to commit."
        fi

        # Push branch: use --force-with-lease to avoid overwriting remote unexpectedly.
        echo "Pushing branch to origin ($TARGET_BRANCH)..."
        git push --set-upstream origin "$TARGET_BRANCH" --force-with-lease

        # Create PR (idempotent-ish: will error if PR exists — we handle it)
        echo "Creating Pull Request..."
        PR_TITLE='refineit: suggested import fixes'
        PR_BODY='Automated fixes produced by RefineIt. Please review before merging.'
        CREATE_RESPONSE=$(curl -s -o /dev/stderr -w "%{http_code}" -X POST \
          -H "Authorization: token ${{ inputs.push_token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d "$(jq -n --arg t "$PR_TITLE" --arg h "$TARGET_BRANCH" --arg b "$BASE_BRANCH" --arg body "$PR_BODY" '{title:$t, head:$h, base:$b, body:$body}')" || true)

        # If curl not installed or jq missing, fallback simple POST (ignore errors)
        if [ -z "$CREATE_RESPONSE" ] || [ "$CREATE_RESPONSE" -eq 0 ]; then
          # fallback (best-effort)
          curl -s -X POST -H "Authorization: token ${{ inputs.push_token }}" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls -d "{\"title\":\"$PR_TITLE\",\"head\":\"$TARGET_BRANCH\",\"base\":\"$BASE_BRANCH\",\"body\":\"$PR_BODY\"}" || true
        fi

        echo "Done."
      shell: bash
