    - name: Create branch & PR
      if: inputs.create-pr == 'true' && inputs.push_token != ''
      run: |
        set -euo pipefail

        # ensure --apply present
        echo "Verifying --apply present in args"
        echo "${{ inputs.args }}" | grep -q -- '--apply' || (echo "Refuse: --apply not present. Aborting." && exit 1)

        # 1. Git config for bot
        git config user.name "refineit-bot"
        git config user.email "ci@refineit.local"

        TARGET_BRANCH="${{ inputs.push-branch }}"
        if [ -z "$TARGET_BRANCH" ]; then
          TARGET_BRANCH="refineit/auto-fixes"
        fi
        BASE_BRANCH="main"

        # Authenticated URL for pushing
        REMOTE_URL="https://x-access-token:${{ inputs.push_token }}@github.com/${{ github.repository }}"
        git remote set-url origin "$REMOTE_URL"

        # 2. Fetch latest refs (do NOT fetch into checked-out branch)
        echo "Fetching latest origin/${BASE_BRANCH}..."
        git fetch --no-tags --prune origin "${BASE_BRANCH}"

        # 3. Create new target branch from origin/BASE_BRANCH
        # If the local branch exists, delete it then create fresh from origin/BASE_BRANCH.
        if git rev-parse --verify --quiet "refs/heads/${TARGET_BRANCH}" >/dev/null; then
          echo "Deleting existing local branch ${TARGET_BRANCH}"
          git branch -D "${TARGET_BRANCH}"
        fi

        echo "Creating branch ${TARGET_BRANCH} from origin/${BASE_BRANCH}"
        git checkout -b "${TARGET_BRANCH}" "origin/${BASE_BRANCH}"

        # 4. Commit changes if any (these are the modifications applied by refineit earlier)
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "refineit: apply suggested fixes" || echo "Nothing to commit (commit failed)."
        else
          echo "No changes detected after refineit --apply. Nothing to push."
        fi

        # 5. Push branch to origin using force-with-lease (safer than plain --force)
        # If there are no local commits, skip push
        if git rev-list --max-parents=0 --count HEAD >/dev/null 2>&1; then
          # just attempt push if branch exists remotely or local has commits
          echo "Pushing branch ${TARGET_BRANCH} to origin..."
          git push --set-upstream origin "${TARGET_BRANCH}" --force-with-lease || {
            echo "Push failed. Attempting to show remote ref info for debugging..."
            git ls-remote origin refs/heads/"${TARGET_BRANCH}" || true
            exit 1
          }
        else
          echo "No local commits, skipping push."
        fi

        # 6. Create PR via GitHub API (idempotent attempt)
        echo "Creating PR from ${TARGET_BRANCH} -> ${BASE_BRANCH}..."
        PR_TITLE="refineit: suggested import fixes"
        PR_BODY="Automated fixes suggested and applied by RefineIt.\n\nSee attached report artifact in workflow run for details."
        # Use a safe check to avoid duplicate PRs
        EXISTING_PR=$(curl -s -H "Authorization: token ${{ inputs.push_token }}" -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.actor }}:${TARGET_BRANCH}&base=${BASE_BRANCH}" | jq -r '.[0].html_url // empty')

        if [ -n "$EXISTING_PR" ]; then
          echo "PR already exists: $EXISTING_PR"
        else
          # create PR
          CREATE_RESP=$(curl -s -X POST -H "Authorization: token ${{ inputs.push_token }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "$(jq -nc --arg t "$PR_TITLE" --arg h "$TARGET_BRANCH" --arg b "$BASE_BRANCH" --arg body "$PR_BODY" '{title: $t, head: $h, base: $b, body: $body}')")

          PR_URL=$(echo "$CREATE_RESP" | jq -r '.html_url // empty')
          if [ -n "$PR_URL" ]; then
            echo "PR created: $PR_URL"
          else
            echo "Failed to create PR. Response:"
            echo "$CREATE_RESP"
            exit 1
          fi
        fi
      shell: bash
