# .github/actions/refineit-action/action.yml
name: "RefineIt (run analyzer)"
description: "Run the RefineIt static analyzer. Optionally create a PR with fixes."
author: "RefineIt Team"

inputs:
  args:
    description: "Extra CLI args"
    required: false
    default: "--dry-run --export-report refineit-report.json"
  create-pr:
    description: "If 'true', create PR"
    required: false
    default: "false"
  push-branch:
    description: "Branch name (if empty, defaults to refineit/auto-fixes)"
    required: false
    default: ""
  working-directory:
    description: "Path"
    required: false
    default: "."
  push_token:
    description: "GitHub token (used to push/create PR)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        cache: "npm"

    - name: Move to working directory
      if: ${{ inputs.working-directory != '.' }}
      run: |
        cd "${{ inputs.working-directory }}"
      shell: bash

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci --silent --no-audit --no-fund
          npm run build
        fi
      shell: bash

    - name: Run RefineIt analyzer
      id: run_refineit
      run: |
        set -euo pipefail

        # Remove ephemeral/CI artifacts to avoid dirty-workspace detection
        rm -rf dist *.tsbuildinfo refineit-report.json refineit-debug.json || true

        # Clean untracked files and reset working tree (best-effort)
        git clean -fdx || true
        git reset --hard || true

        echo "Running: npx refineit ${{ inputs.args }}"
        # Run refineit but do not fail the step (we want to upload artifacts)
        npx refineit ${{ inputs.args }} || true
      shell: bash

    - name: Upload report artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: refineit-report
        path: |
          refineit-report.json
          refineit-debug.json
        retention-days: 7

    - name: Create branch & PR
      if: ${{ inputs.create-pr == 'true' && inputs.push_token != '' }}
      run: |
        set -euo pipefail

        # Require --apply for safety
        echo "${{ inputs.args }}" | grep -q -- '--apply' || (echo "Refuse: --apply not present. Aborting." && exit 1)

        git config user.name "refineit-bot"
        git config user.email "ci@refineit.local"

        # Determine target branch (fallback to refineit/auto-fixes)
        TARGET_BRANCH="${{ inputs.push-branch }}"
        if [ -z "$TARGET_BRANCH" ]; then
          TARGET_BRANCH="refineit/auto-fixes"
        fi
        BASE_BRANCH="main"

        # Configure authenticated remote (uses the provided push token)
        REMOTE_URL="https://x-access-token:${{ inputs.push_token }}@github.com/${{ github.repository }}"
        git remote set-url origin "$REMOTE_URL"

        # Fetch remote refs safely (do not fetch into local checked-out branch)
        git fetch --no-tags origin "$BASE_BRANCH" || true
        git fetch --no-tags origin "$TARGET_BRANCH" || true

        # Create fresh branch from origin/$BASE_BRANCH if it exists
        if git ls-remote --exit-code --heads origin "$BASE_BRANCH" >/dev/null 2>&1; then
          git checkout -b "$TARGET_BRANCH" "origin/$BASE_BRANCH"
        else
          git checkout -b "$TARGET_BRANCH"
        fi

        # If there are repository changes (applied by refineit), commit & push them
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "refineit: apply suggested fixes"

          echo "Changes detected and committed. Pushing branch..."
          git push --set-upstream origin "$TARGET_BRANCH" --force-with-lease

          # Build PR JSON (no external deps)
          read -r -d '' PR_BODY <<'JSON' || true
{"title":"refineit: suggested fix applied","head":"'"$TARGET_BRANCH"'","base":"'"$BASE_BRANCH"'","body":"Automated fixes from RefineIt."}
JSON

          echo "Attempting to create Pull Request (response follows) ..."
          # Use curl silent+show-error; do NOT use -v (avoids exposing headers)
          RESPONSE=$(curl -sS -X POST -H "Authorization: token ${{ inputs.push_token }}" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls -d "$PR_BODY" || true)
          echo "PR API response: $RESPONSE"
        else
          echo "No changes to commit. Skipping branch push and PR creation."
        fi
      shell: bash
