name: "RefineIt (run analyzer)"
description: "Run the RefineIt static analyzer. Optionally create a PR with fixes."
author: "RefineIt Team"
inputs:
  args:
    description: "Extra CLI args"
    required: false
    default: '--dry-run --export-report refineit-report.json'
  create-pr:
    description: "If 'true', create PR"
    required: false
    default: 'false'
  push-branch:
    description: "Branch name"
    required: false
    default: ''
  working-directory:
    description: "Path"
    required: false
    default: '.'
  push_token:
    description: "GitHub token"
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Move to working directory
      if: inputs.working-directory != '.'
      run: cd "${{ inputs.working-directory }}"
      shell: bash

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci --silent --no-audit --no-fund
          npm run build
        fi
      shell: bash

    - name: Run RefineIt analyzer
      id: run_refineit
      run: |
        set -e
        
        # Cleanup step to ensure the workspace is clean before the analysis
        rm -rf dist *.tsbuildinfo refineit-report.json refineit-debug.json || true
        git checkout .
        
        echo "Running: npx refineit ${{ inputs.args }}"
        npx refineit ${{ inputs.args }} || true
      shell: bash

    - name: Upload report artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: refineit-report
        path: |
          refineit-report.json
          refineit-debug.json
        retention-days: 7

    - name: Create branch & PR
      if: inputs.create-pr == 'true' && inputs.push_token != ''
      run: |
        set -e
        
        # Check if the --apply flag is present to ensure safety
        echo "Verifying --apply present in args"
        echo "${{ inputs.args }}" | grep -q -- '--apply' || (echo "Refuse: --apply not present. Aborting." && exit 1)

        # 1. Configuration 
        git config user.name "refineit-bot"
        git config user.email "ci@refineit.local" # Use dedicated bot email
        
        TARGET_BRANCH="refineit/auto-fixes"
        BASE_BRANCH="main"
        
        # Define the authenticated URL for pushing
        REMOTE_URL="https://x-access-token:${{ inputs.push_token }}@github.com/${{ github.repository }}"
        git remote set-url origin "$REMOTE_URL"

        # 2. Preparation: Ensure we are starting from the latest base branch
        git fetch origin $BASE_BRANCH:$BASE_BRANCH
        git fetch origin "$TARGET_BRANCH" || true
        
        # 3. Create/Reset the Branch
        # Force delete local branch if it exists, then check out from the remote base
        if git show-ref --verify --quiet "refs/heads/$TARGET_BRANCH"; then
          git branch -D "$TARGET_BRANCH"
        fi
        git checkout -b "$TARGET_BRANCH" "origin/$BASE_BRANCH"

        # 4. Commit Changes (Files modified by 'npx refineit --apply' earlier)
        # This step commits the changes applied in the previous analysis step.
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "refineit: apply suggested fixes"
        fi

        # 5. Push Safely (Fixes "non-fast-forward" error)
        # --force-with-lease pushes only if the remote branch hasn't been updated unexpectedly.
        git push --set-upstream origin "$TARGET_BRANCH" --force-with-lease

        # 6. Create PR (Only if the push succeeded)
        PR_BODY='{"title":"refineit: suggested import fixes","head":"'"$TARGET_BRANCH"'","base":"'"$BASE_BRANCH"'","body":"Automated fixes."}'
        curl -s -X POST -H "Authorization: token ${{ inputs.push_token }}" -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls -d "$PR_BODY" > /dev/null
      shell: bash